import pandas as pd
import argparse
import os
import sys

def analyze_clusters(filename):
    """
    Analyzes cluster winners by comparing DSP parameters, average score, and reward.
    """
    try:
        df = pd.read_csv(filename)
    except Exception as e:
        print(f"Error reading {filename}: {e}")
        sys.exit(1)
    
    # Identify DSP columns (those starting with 'dsp_')
    dsp_cols = [col for col in df.columns if col.startswith('dsp_')]
    
    # Columns we want to aggregate
    # 'score' and 'bonus' are standard, 'reward' is also useful
    metrics = ['score', 'bonus']
    if 'reward' in df.columns:
        metrics.append('reward')
    
    agg_cols = metrics + dsp_cols
    
    # Check if 'cluster' column exists
    if 'cluster' not in df.columns:
        # Fallback to 'cluster_id' if that's what's in the CSV
        if 'cluster_id' in df.columns:
            df = df.rename(columns={'cluster_id': 'cluster'})
        else:
            print("Error: 'cluster' or 'cluster_id' column not found in CSV.")
            print(f"Available columns: {df.columns.tolist()}")
            sys.exit(1)

    # Filter out rows with no cluster information if any
    df = df.dropna(subset=['cluster'])
    
    # Group by cluster and calculate mean
    summary = df.groupby('cluster')[agg_cols].mean()
    
    # Add count of samples per cluster
    summary['count'] = df.groupby('cluster').size()
    
    # Calculate success rate if we had the original non-winners, 
    # but since this is @get_winners.py output, every row is a success (score >= 0.5)
    
    # Reorder columns for better readability: Count first, then metrics, then DSP params
    ordered_cols = ['count'] + metrics + dsp_cols
    summary = summary[ordered_cols]
    
    return summary

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Analyze cluster winners to understand DSP differentiation.")
    parser.add_argument('-f', '--filename', required=True, help='Path to the winners CSV file (generated by get_winners.py)')
    args = parser.parse_args()
    
    if not os.path.exists(args.filename):
        print(f"Error: File {args.filename} not found.")
        sys.exit(1)
        
    print(f"Analyzing clusters in {args.filename}...")
    summary = analyze_clusters(args.filename)
    
    # Generate output filename
    base = os.path.basename(args.filename)
    name, ext = os.path.splitext(base)
    output_filename = f"analysis_{name}.csv"
    
    # Save to CSV
    summary.to_csv(output_filename)
    
    # Print a nice summary to console
    print("\n" + "="*80)
    print(f"CLUSTER DIFFERENTIATION SUMMARY (Averages)")
    print("="*80)
    # Using to_string for better formatting in console
    print(summary.to_string())
    print("="*80)
    print(f"Summary saved to: {output_filename}")
    
    # Brief interpretation
    print("\nQuick Interpretation:")
    if not summary.empty:
        # Find the cluster with highest average score
        best_score_cluster = summary['score'].idxmax()
        # Find the cluster with most winners
        most_winners_cluster = summary['count'].idxmax()
        
        print(f"- Cluster {best_score_cluster} has the HIGHEST average score ({summary.loc[best_score_cluster, 'score']:.4f}).")
        print(f"- Cluster {most_winners_cluster} has the MOST winners ({summary.loc[most_winners_cluster, 'count']}).")
        
        # Check for DSP variance
        if dsp_cols:
            print("- Look at the dsp_* columns to see which acoustic profiles require stronger manipulations.")
